### ISSUE TITLE
Can't get it installed

### ISSUE THREAD

**Issue by Quikko** [angular-university/angular-security-course#3]
Hi there,

After given the command to launch the back-end server (npm run server
), I receive following error:

![selection_096](https://user-images.githubusercontent.com/17740503/38641376-1cd7765a-3dd7-11e8-88d3-ba8203875d9e.jpg)

Any idea how to solve this?

Greetingz

**Comment by abdelrahmanlifestyle** [comment]
I had the same issue and solved by installing Visual Studio Enterprise 2015 (The issue of because of no  C++ compiler).

**Comment by KyawKyawLwinThant** [comment]
ft Windows [Version 10.0.17763.737]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\angular_security\angular-security-course>npm cache clean --froce
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'np
m cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking th
e actual one.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2019-09-29T14_58_02_940Z-debug.log

D:\angular_security\angular-security-course>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

D:\angular_security\angular-security-course>npm install

> argon2@0.16.2 install D:\angular_security\angular-security-course\node_modules\argon2
> node-gyp rebuild


D:\angular_security\angular-security-course\node_modules\argon2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\hp\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\angular_security\angular-security-course\node_modules\argon2
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN codelyzer@4.2.1 requires a peer of @angular/compiler@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.2.1 requires a peer of @angular/core@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.2.1 requires a peer of @angular/platform-browser-dynamic@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.2.1 requires a peer of @angular/platform-browser@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.2.1 requires a peer of @angular/common@>=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.16.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2019-09-29T15_00_10_359Z-debug.log

D:\angular_security\angular-security-course>

**Comment by bleuscyther** [comment]
If you are on windows you can try:
````console
npm install --global --production windows-build-tools
````
or better:
````console
npm --add-python-to-path i -g windows-build-tools
````
as suggeted here https://github.com/angular-university/angular-security-course/issues/5#issuecomment-434867761

With admin privileges. I had it installed but seems  that it stopped working when i installed another VisualStudio

**Comment by bleuscyther** [comment]
Also you can get update argon2 i think. It fixes the installation process on **Windows10** + **Python 2.7** + **NodeJs12**
